name: Update Parent Repository

on:
  push:
    branches:
      - main  

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v2

      - name: Checkout Parent Repository
        uses: actions/checkout@v2
        with:
          repository: MuneerAhmed03/MindR
          path: ../parent-repo 

      - name: Update Frontend Submodule in Parent Repository
        run: |
          cd ../parent-repo
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add mindr-app  
          git commit -m "Update frontend submodule to latest commit" --allow-empty  
          git push origin main  
